version: '3.8'
services:
  player:
    build: ./player
    volumes:
      - /media/usb:/media/usb:ro
    devices:
      - "/dev/fb0:/dev/fb0"
    environment:
      - DISPLAY=:0
    restart: always

  web-gallery-backend:
    build: ./web-gallery/backend
    volumes:
      - /media/usb:/media/usb
    ports:
      - "5000:5000"
    restart: always

  web-gallery-frontend:
    build: ./web-gallery/frontend
    ports:
      - "80:80"
    depends_on:
      - web-gallery-backend
    restart: always

  dns:
    image: andyshinn/dnsmasq
    volumes:
      - ./dns-server/dnsmasq.conf:/etc/dnsmasq.conf
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    restart: always
