version: '3.8'

services:
  player:
    build: ./player
    volumes:
      - /media/usb:/media/usb:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - "/dev/fb0:/dev/fb0"
    environment:
      - DISPLAY=:0
      - SDL_VIDEODRIVER=x11
      - SDL_FBDEV=/dev/fb0
      - SDL_AUDIODRIVER=dummy
    privileged: true
    stdin_open: true
    tty: true
    restart: always

  web-gallery-backend:
    build: ./web-gallery/backend
    volumes:
      - /media/usb:/media/usb
    ports:
      - "5000:5000"
    restart: always

  web-gallery-frontend:
    build: ./web-gallery/frontend
    ports:
      - "80:80"
    depends_on:
      - web-gallery-backend
    restart: always

  dns:
    build: ./dns-server
    network_mode: "host"     # nutné pro správnou funkci dnsmasq
    cap_add:
      - NET_ADMIN
    restart: always
