services:
  player:
    build: ./player
    volumes:
      - /media/usb:/media/usb:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/runtime-dir:/tmp/runtime-dir
    devices:
      - "/dev/fb0:/dev/fb0"
      - "/dev/snd:/dev/snd"
    environment:
      - DISPLAY=:0
      - XDG_RUNTIME_DIR=/tmp/runtime-dir
    restart: always


  web-gallery-backend:
    build: ./web-gallery/backend
    volumes:
      - /media/usb:/media/usb
    ports:
      - "5000:5000"
    restart: always

  web-gallery-frontend:
    build: ./web-gallery/frontend
    ports:
      - "80:80"
    depends_on:
      - web-gallery-backend
    restart: always

  dns:
    build: ./dns-server
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    restart: always
