services:
  player:
    build: ./player
    volumes:
      - /media/usb:/media/usb:ro
      - /tmp/.X11-unix:/tmp/.X11-unix   # připojení X socketu
    devices:
      - "/dev/fb0:/dev/fb0"
      - "/dev/snd:/dev/snd"             # pro zvuk, pokud bude potřeba
    environment:
      - DISPLAY=:0
    restart: always

  web-gallery-backend:
    build: ./web-gallery/backend
    volumes:
      - /media/usb:/media/usb
    ports:
      - "5000:5000"
    restart: always

  web-gallery-frontend:
    build: ./web-gallery/frontend
    ports:
      - "80:80"
    depends_on:
      - web-gallery-backend
    restart: always

dns:
  build: ./dns-server
  network_mode: "host"
  cap_add:
    - NET_ADMIN
  restart: always
