version: '3.8'

services:

  web-gallery-backend:
    build: ./web-gallery/backend
    volumes:
      - /media/usb:/media/usb
    ports:
      - "5000:5000"
    restart: always

  web-gallery-frontend:
    build: ./web-gallery/frontend
    ports:
      - "80:80"
    depends_on:
      - web-gallery-backend
    restart: always